#!/bin/bash

RESPONSE_FILE="liste-bot.txt"

if [[ $# -gt 2 ]]; then #Verifies the number of arguments given, if more than 2, send out an error to sterr
    echo "<< chat-bot destinataire [pseudo] >>" >&2
    exit 1
fi

username=$1
bot_name=${2:-bot}
# Create named pipes
mkfifo pipe1 pipe2

function chat_bot() {
    input="$@"
    case "$input" in
        liste)
            while read -r line; do
                echo "$line"
            done < <(ls)
            ;;
        li*)
            file=$(echo "${input#li}" | xargs) # xargs is for removing spaces (leading/trailing)
            if [[ -f "$file" && -r "$file" ]]; then #exists? readable?
                cat "$file"; echo # echo forces cat to end in a new line(if not, it's ugly)
            else
                echo "Sorry, this file doesn't exist or the file isn't readable" >&2
                exit 2
            fi
            ;;
        "qui suis-je")
            echo "$username"
            ;;
        
        "au revoir")
            echo "Au revoir!"
            exit 0
            ;;
        *)
            if grep -w -q "$input" "$RESPONSE_FILE"; then #Reminder to implement check -r for response-file and if it exists ofc
                # if that word is found in RESPONSE_FILE
                grep "$input" "$RESPONSE_FILE" | while read -r line; do
                    # Extract everything after the first space in the line
                    # cuz reponse starts after 1st space
                    answer="${line#* } "
                    echo "$answer"
                done
            else
                echo "🤖 ?"
            fi
            ;;
    esac
}


./chat $username $bot_name &
./chat $bot_name $username --bot < pipe1 > pipe2 &
 
# Clean up pipes on script exit
trap "rm pipe1 pipe2; kill $!" EXIT

while true; do
    read -p "$username: " usermessage
    chat_bot "$usermessage"
done

rm pipe1 pipe2
